project_name: convertStrCases
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: convertToKebab
    main: ./cmd/convertToKebab/main.go
    binary: convertToKebab
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
  - id: convertToLowerCamel
    main: ./cmd/convertToLowerCamel/main.go
    binary: convertToLowerCamel
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
  - id: convertToSnake
    main: ./cmd/convertToSnake/main.go
    binary: convertToSnake
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
  - id: convertToUpperCamel
    main: ./cmd/convertToUpperCamel/main.go
    binary: convertToUpperCamel
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
